site_name: Workstation
site_description: Documentation for Workstation
repo_url: https://github.com/square/workstations
repo_name: "square/workstations"
edit_uri: "https://github.com/square/workstations/blob/main/docs/docs/"
strict: false
#test
####################################################################################################
# Glad you're here. Some house rules:
# - The top-level tabs should stay lean. If you're adding more, get someone to peer review.
# - Maintain alphabetical ordering. Each top-level section has the following in this order:
#   - A welcome page
#   - Second-level sections
#   - Standalone pages
# - Feel free to add a page to multiple top-level sections, if it's appropriate, but please try to keep a maximum of 3 levels.
# - If you are moving a page's URL (i.e. its location in the repo), add a redirect. There's a place
#   list of redirects below.
# - Suffix external links in nav with ↗.
####################################################################################################

nav:
  - Home:
    - index.md
  - Issues:
    - https://github.com/square/workstations/issues
  - Developer Docs: api.md
  - Command Line Usage:
    - cli.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/cashapp.png
  features:
    - search.highlight
    - search.suggest
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.expand
    - content.tabs.link
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: green
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: green
      toggle:
        icon: material/eye
        name: Switch to light mode
  static_templates:
    - 404.html
extra_css:
  - "css/app.css"
extra_javascript:
  - "js/all-pages.js"
extra:
  repo_icon: bitbucket
  search:
    tokenizer: '[\s\-\.]+'
    prebuild_index: true
  analytics:
    provider: google
    property: "UA-163700149-1"
markdown_extensions:
  mkdocs-click:
  pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  abbr:
  footnotes:
  admonition:
  attr_list:
  codehilite:
    guess_lang: false
  def_list:
  markdown_include.include:
  md_in_html:
  meta:
  pymdownx.betterem:
    smart_enable: all
  pymdownx.caret:
  pymdownx.inlinehilite:
  pymdownx.magiclink:
    repo_url_shortener: true
    repo_url_shorthand: true
    social_url_shorthand: true
    social_url_shortener: true
    user: squareup
    normalize_issue_symbols: true
  pymdownx.smartsymbols:
  pymdownx.superfences:
  pymdownx.details:
  pymdownx.critic:
  pymdownx.tabbed:
    alternate_style: true
  smarty:
  tables:
  pymdownx.tasklist:
    clickable_checkbox: true
    custom_checkbox: true
  toc:
    permalink: true
plugins:
  autorefs:
  tags:
  mkdocstrings:
    handlers:
      python:
        paths: ["../src/workstation",]
  search:
    lang: en
  redirects:
    redirect_maps:
